language: r
sudo: required
dist: trusty
cache:
#  - packages
  - ccache

r:
  - release
  - devel
  - oldrel

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - devscripts # checkbashisms
      - libgdal-dev
      - libproj-dev
      - libgeos-dev
      - libudunits2-dev
      - libnetcdf-dev
      - netcdf-bin
